### ISSUE TITLE
Document installation instructions

### ISSUE THREAD

**Issue by NomarCub** [joethei/browser-link-favicons#8]
It took me a while to figure out how to install the extension on Chrome.
With the most recent version not being available in the Firefox store yet, I don't know if I even can install it on a normal Firefox. ([This](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) is what I found.)

**Comment by joethei** [comment]
It's available now, normally a new version is available within 24 hours of me submitting it.

I probably won't provide install instructions outside the official stores.
